### ISSUE TITLE
Console Spam

### ISSUE THREAD

**Issue by TylerS1066** [Dandielo/dtlCore#2]
I am running a paper-spigot 1.9.2 server, with dtltraders and core (1.9 beta update).

The console spams out the names of every item in a persons inventory when they open, close, buy or sell with the NPC.

This is really annoying when trying to use the console, or when trying to dig through the logs that have become 1+ GB each.

These are the plugins I run:
AP_Turrets v2.0.0
AreaShop v2.2.2
Autorank v3.6
Beaming v1.03
Bounty v4.1.2
Brewery v1.4.4
BuycraftX v10.1.1
CBWrapper v1.8.3
Citizens v2.0.17-SNAPSHOT (build 1362)
ClearLag v2.9.1
CoreProtect v2.12.0
CreeperHeal v6.8.1
CustomWhiteList v1.3-release
Deadbolt v2.2
dtlCore v1.0.1-beta
dtlTraders v3.4.0-beta
EnjinMinecraftPlugin v2.7.7
Essentials vTeamCity
EssentialsGeoIP vTeamCity
EssentialsProtect vTeamCity
EssentialsSpawn vTeamCity
Factions v2.8.2
Herochat v5.6.7-SNAPSHOT
iFill v0.1.0
MassiveCore v2.8.2
Movecraft v4.6.0
OpenInv v2.3.6-vk-1_10_R1
PermissionsEx v1.23.4
PlayerHeads v3.10-SNAPSHOT-jenkins-PlayerHeads-1-61-g39b94b4
PlugMan v2.1.1
ProtocolLib v4.0.1
ResPwn v1.1
SamistineSignFix v2.2
Sentry v1.9.0
StructureInABox v1.1.1
VanishNoPacket v3.20
Vault v1.5.6-b49
WGBlockRestricter v2.0
WGCustomFlags v1.8.1-beta
WGFactions v0.1.1
WGLandClaim v1.3
WorldBorder v1.8.4
WorldEdit v6.1.1-SNAPSHOT;3482-867e59b
WorldGuard v6.1 with custom flags plugin.

**Comment by NathanWolf** [comment]
Is there anything in the log to indicate what plugin it's coming from? That doesn't really sound like Magic, though I will double check the dtlTraders integration for leftover debug logs.

The Traders integration is broken by the way, and unfortunately that plugin will destroy all Magic items.

**Comment by TylerS1066** [comment]
Where did you see Magic?

I am 99% sure that it is dtlTraders, because watching console it only happens when you open a merchant, buy from one, sell to one, or when you close it.

**Comment by NathanWolf** [comment]
Oh sorry! I forgot I get notifications here, don't mind me.

**Comment by TylerS1066** [comment]
Solved this issue by updating to 3.4.3, but it wiped all durability data on items.  Which ruined all of our "blacksmith" NPCs that sell tools and such.  Say goodbye to yet another afternoon...
